name:                collocations
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/k-bx/collocations#readme
license:             BSD3
author:              Kostiantyn Rybnikov
maintainer:          k-bx@k-bx.com
copyright:           All Rights Reserved
category:            Unclassified
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - corenlp-parser
  - data-default
  - text
  - trifecta
  - containers
  - Decimal
  - unordered-containers
  - groom

executables:
  collocations:
    source-dirs:      src
    main:             Main.hs
    ghc-options:      -Wall
                      -threaded
                      -with-rtsopts=-N
